# Full k=6 analysis preset - Pure AIS (60 users, 60 hours with 4-process parallel)

data_root: "data/ExtraSensory.per_uuid_features_labels"
out_dir: "analysis/out/k6_full_<STAMP>"

# Full analysis scope
n_users: 60
feature_modes: [composite]  # Single mode for k=6 analysis

# Quality control profile
quality_profile: "balanced"  # Recommended for production

# Time delays
taus: [1, 2]

# Pure AIS k-selection (no constraints)
k_selection:
  strategy: "AIS"
  k_grid: [1, 2, 3, 4, 5, 6]
  k_max: null  # No hard cap
  undersampling_guard: false  # Disabled for pure AIS

# CTE configuration (6-bin stratification)
hour_bins: 6
conditional_transfer_entropy:
  hour_bins: 6
  bin_definitions:
    0: "00:00-04:00"
    1: "04:00-08:00"
    2: "08:00-12:00"
    3: "12:00-16:00"
    4: "16:00-20:00"
    5: "20:00-24:00"
  method: "STRATIFIED-CTE"

# Surrogate testing
surrogates: 1000

# FDR correction
fdr:
  families: [TE, CTE, STE, GC]
  by_tau: true
  alpha: 0.05

# JVM configuration (validated for k=6)
jvm:
  xms: "6g"
  xmx: "12g"  # Minimum for k=6
  opts:
    - "-XX:+UseG1GC"
    - "-XX:MaxGCPauseMillis=300"
    - "-Djava.awt.headless=true"

# Runtime settings
runtime:
  checkpoint: true
  heartbeat_interval: 60

schema_version: "v1.0"
