# Single-user run for 0E6184E1 (non-resume), to complete missing True CTE rows

data_root: "analysis/temp_single_user_0E6184E1_data"
out_dir: "analysis/out/single_user_0E6184E1_<STAMP>"

n_users: 1
feature_modes: [composite]

quality_profile: "balanced"
taus: [1, 2]

hour_bins: 6

k_selection:
  strategy: "AIS"
  k_grid: [1, 2, 3, 4, 5, 6]
  k_max: 6
  undersampling_guard: true

surrogates: 10000
statistical:
  adaptive_surrogates:
    enabled: true
    stages: [1000, 3000, 10000]
    p_sig: 0.01
    p_nonsig: 0.20

fdr:
  families: [TE, TRUE_CTE]
  by_tau: true
  alpha: 0.05

jvm:
  xms: "4g"
  xmx: "8g"
  opts:
    - "-XX:+UseG1GC"
    - "-XX:MaxGCPauseMillis=300"
    - "-Djava.awt.headless=true"

runtime:
  concurrency: 1
  checkpoint: true
  heartbeat_interval: 60

analysis_modes: [global_te, true_cte]

schema_version: "v1.0"

